applications/persona/urls.py
from django.urls import path
from . import views

# le damos un nombre a todas las urls
app_name = 'persona_app'

urlpatterns = [
    #incio base de tempaltes
        path('', views.InicioView.as_view(), name='inicio' ),



    #list views
    path('listar-todo-empleado/', views.ListAllEmpleados.as_view(), name="empleados_all"),

    path('listar-empleado-admin/', views.ListAllEmpleadosAdmin.as_view(), name="empleados_admin"),

    
    path('listar-by-area/<short_name>', views.ListByArea.as_view(),name='empleado_area'),
    path('listar-by-work/<job>', views.ListByWork.as_view()),
    path('listar-by-kword/', views.ListarEmpleadoPorPalabraClave.as_view()),
    path('listar-by-habilidades/', views.ListHabilidadesEmpleados.as_view()),


    #details view
    
    path('ver-empleado/<pk>', views.EmpleadoDetailView.as_view(), name='empleado_detail'),
    
    #create view
    
    path('add_empleado/', views.EmpleadoCreateView.as_view(), name="add_empleado"),


    #                                                  le etiqueda name nos da la oportunidad de referirnos a esta url mediante el resver_lazy
    path('sucess/', views.SusscessView.as_view(), name='correcto' ),
    #update view
    path('update/<pk>', views.EmpleadoUpdateView.as_view(), name='update' ),
    #deleteview
    path('delete/<pk>', views.EmpleadoDeleteView.as_view(), name='delete' ),





   


]

empleado/urls.py
from django.contrib import admin
from django.urls import path, include
from applications.home.views import IndexView
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    #home
    path('', include('applications.home.urls')),
    path('', include('applications.persona.urls')),
    path('', include('applications.departamento.urls')),



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/persona/models.py
from django.db import models
from applications.departamento.models import Departamento
from ckeditor.fields import RichTextField


# Create your models here.

class Habilidades(models.Model):
    habilidad = models.CharField('Habilidad',max_length=50)


    class Meta():
        verbose_name = 'Habilidad'
        verbose_name_plural = 'Habilidades empleado'

    def __str__(self):
        return str(self.id) + '-' + self.habilidad 




class Empleado(models.Model):
    """ Modelo para tabla de empleados    """
    JOB_CHOICES = (
        ('0','CONTADOR'),
        ('1','ADMINISTRADOR'),
        ('2','ECONOMISTA'),
        ('3','OTRO')
    )
    #contador
    #administrador
    #economista
    #otro
    first_name = models.CharField('Nombres', max_length=60)
    last_name = models.CharField('Apellido', max_length=60)
    ## se agrega este atributo al modelos
    full_name = models.CharField('nombres completos', max_length=120, blank=True, null=True)
    #aqui creamos un apartado donde se puede elegir el tipo de trabajo en la bse de datos del administrador
    job = models.CharField('trabajo', max_length=1, choices=JOB_CHOICES )
    #aqui creamos la relacion entra la base de datos de los departamentos y los empleados
    #relacion de uno a muchos
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)

    avatar = models.ImageField( upload_to='empleado',blank=True, null=True )
    
    
    
    habilidades = models.ManyToManyField(Habilidades)
    hoja_vida = RichTextField()
    class Meta():
        verbose_name = 'Empleados'
        verbose_name_plural = 'Empleados de la empresa'
    
    def __str__(self):
        return str(self.id) + '-' + self.first_name + '-' + self.last_name    

applications/persona/forms.py
from django import forms

from .models import Empleado

class EmpleadoForm(forms.ModelForm):
    """Form definition for empleado."""

    class Meta:
        """Meta definition for empleadoform."""

        model = Empleado
        fields = ('first_name',
                  'last_name',
                  'full_name',
                  'job',
                  'departamento',
                  'avatar',
                   'habilidades',
                  )
        
        widgets = {
            'habilidades':forms.CheckboxSelectMultiple()

        }
        

applications/persona/views.py
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, TemplateView, UpdateView, DeleteView
from .models import Empleado
from django.urls import reverse_lazy
from .forms import EmpleadoForm

# Create your views here.


class InicioView(TemplateView):
    template_name = "inicio.html"



#requiere de un template html
class ListAllEmpleados(ListView):
    template_name = 'persona/list_all.html'
    paginate_by = 4
    ordering = 'first_name'
    context_object_name = 'empleados'

    def get_queryset(self):
                                        #vvvvv este parametro tiene que ser el mismo informado en el input
        palabra_clave = self.request.GET.get("kword", '')
        ##creamos una lista filtrada donde la palabra clave recogida por le metodo get tiene que ser igual al atributo en la base de datos
        lista = Empleado.objects.filter(
            first_name__icontains=palabra_clave
        ) 

        return lista


#requiere de un template html
class ListAllEmpleadosAdmin(ListView):
    model = Empleado    
    template_name = 'persona/lista_empleados.html'
    paginate_by = 10
    ordering = 'first_name'
    context_object_name = 'empleados'



 #requiere de un template html
class ListByArea(ListView):
 #lista empleados de area en especifico
    template_name = 'persona/list_by_area.html'
    context_object_name ="empleados"
 
    # metodo para hacer listado de forma dinamica
    def get_queryset(self):
        #kwargs recupera del url lo que se estan mandando
        area = self.kwargs['short_name']
        #creamos un filtro interactuando con el navegador
        lista = Empleado.objects.filter(
        departamento__short_name = area
 ) 
        return lista




class ListByWork(ListView):
 #lista empleados de area en especifico
    template_name = 'persona/list_by_work.html'
 
    # metodo para hacer listado de forma dinamica
    def get_queryset(self):
        #kwargs recupera del url lo que se estan mandando
        area = self.kwargs['job']
        #creamos un filtro interactuando con el navegador
        lista = Empleado.objects.filter(job__name=area) 
        return lista
    



class ListarEmpleadoPorPalabraClave(ListView):
 #lista empleados por palabra clave
    template_name = 'persona/list_by_kword.html'
    context_object_name = 'empleado'


    # metodo para hacer listado de forma dinamica
    def get_queryset(self):
        print('************')
                                            #vvvvv este parametro tiene que ser el mismo informado en el input
        palabra_clave = self.request.GET.get("kword", '')
        ##creamos una lista filtrada donde la palabra clave recogida por le metodo get tiene que ser igual al atributo en la base de datos
        lista = Empleado.objects.filter(first_name=palabra_clave) 
        print(lista)
        return lista
    

class ListHabilidadesEmpleados(ListView):
    template_name = 'persona/habilidades.html'
    context_object_name = 'habilidades'

    def get_queryset(self):
        #al utilizar el orm de django vvv recuperamos un unico registro de la base de datos
        id_empleado = self.request.GET.get("nombre", '')
        empleado = Empleado.objects.get(id=id_empleado)
        
        return empleado.habilidades.all()
    



class EmpleadoDetailView(DetailView):
    model = Empleado
    template_name = "persona/detail_empleado.html"

    # de esta forma intervenimos metodos
    def get_context_data(self, **kwargs):
        context = super(EmpleadoDetailView, self).get_context_data(**kwargs)
        #podemos agregar variagles desde aqui
        context['titulo'] = 'empleado del mes'
        return context
    


class SusscessView(TemplateView):
    template_name = "persona/sucess.html"




#necesita de 4 campos para funcionar el create iew
class EmpleadoCreateView(CreateView):
    model = Empleado
    template_name = "persona/add.html"

    #fields = ('__all__') de esta forma jalamos todos los datos del modelo de la base de datos
    form_class = EmpleadoForm
    #success_url = '/sucess' en ves de usar esto, importamos "from django.urls import reverse_lazy"
    success_url = reverse_lazy('persona_app:empleados_admin')


    ## es una forma de interseptar el from valid
    def form_valid(self, form):
        #logica del proceso
        # recoje todos los datos enviados en el formulario y los guarda ene sta variable empleado
        empleado = form.save()
        # de esta forma agregarmos el full name al registro de la base de datos
        empleado.full_name = empleado.first_name + ' ' + empleado.last_name
        empleado.save()
        print(empleado)

        # el super v v se utiliza para sobre escribir un metodo de la class EmpleadoCreateView
        return super(EmpleadoCreateView, self).form_valid(form)



class EmpleadoUpdateView(UpdateView):
    model = Empleado
    template_name = "persona/update.html"
    fields = ['first_name',
              'last_name',
              'job',
              'departamento',
              'habilidades',
              ]
    success_url = reverse_lazy('persona_app:empleados_admin')


    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        print('****** METHOD POSTTT*********')
        print('***************')
        print(request.POST)
        print(request.POST['last_name'])

        return super().post(request, *args, **kwargs)
    def form_valid(self, form):
        #logica del proceso
        print('****** METHOD FORM VALID*********')
        print('***************')
        print('***************')
           # el super v v se utiliza para sobre escribir un metodo de la class EmpleadoCreateView
        return super(EmpleadoUpdateView, self).form_valid(form)



class EmpleadoDeleteView(DeleteView):
    model = Empleado
    template_name = "persona/delete.html"
    success_url = reverse_lazy('persona_app:empleados_admin')

    def delete(self, request, *args, **kwargs):
        """
        Call the delete() method on the fetched object and then redirect to the
        success URL.
        """
        self.object = self.get_object()
        success_url = self.get_success_url()
        self.object.delete()
        return HttpResponseRedirect(success_url)

templates/persona/add.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    registrar empleado
{% endblock title %}



{% block content %}

{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Registrar empleado</h1>
        <div class="cell">
            <form class="cell grid-container grid-margin-x" method="POST" enctype="multipart/form-data"> {% csrf_token %}
                <div class="medium-6 cell">
                    <label>Nombre:
                            {{form.first_name}}
                    </label>
                </div> 
                <div class="medium-6 cell">
                    <label>Apellido:
                            {{form.last_name}}
                    </label>
                </div> 
                <div class="medium-6 cell">
                    <label>Trabajo:
                            {{form.job}}
                    </label>
                </div> 
                <div class="medium-6 cell">
                    <label>Departamento:
                            {{form.departamento}}
                    </label>
                </div> 
                <div class="medium-6 cell">
                    <label>Habilidades:
                            {{form.habilidades}}
                    </label>
                </div> 
                <div class="medium-6 cell">
                    <label>Foto:
                            {{form.avatar}}
                    </label>
                </div> 
                <div class="medium-6 cell">
                    <button class="button success" type="submit"> Registrar </button>
                </div> 
            </form>
    
        </div>
    </div>

</div>
  
{% endblock content %}
    

templates/persona/delete.html
{% extends 'base.html' %}


{% block content %}
  

<div class="grid-container">

    <div class="grid-x">
        <h1 class="cell">Eliminar empleado: {{ object.first_name }} {{ object.last_name }}</h1>
        <form action="" method="post">{% csrf_token %}

            <div class="callout secondary">
                <h5>desea eliminar este empleado?</h5>
                <button type="submit" class="button alert" >eliminar</button>
            </div>

        </form>
    </div>
</div>
{% endblock content %}
    

templates/persona/detail_empleado.html
{% extends 'base.html' %}

{% load static %}


{% block title %}
  {{object.first_name}}   {{object.last_name}}
{% endblock title %}

{% block content %}

{% include 'includes/header.html' %}


<div class="grid-container">
  <div class="grid-x grid-margin-x align-center-middle">
    <div class=" cell large-4 card" style="width: 300px; margin-top: 10px;" >
      <div class="card-divider">
        {{ empleado.get_job_display }}
      </div>
      
      {% if empleado.avatar %}
      <img src="{{empleado.avatar.url}}">
      {% else %}
      <img src="{% static 'img/mesi.jpeg' %}">
      {% endif %}
        
      
      <div class="card-section">
        <h4>{{object.first_name}}   {{object.last_name}}</h4>
        <p>{{ empleado.first_name }}</p>
        <p>{{ empleado.last_name }}</p>
        <p>{{ empleado.job }}</p>
        <p>{{ empleado.departamento.short_name }}</p>
        <p><span class="label"> Habilidades</span></p>
        <ul class="vertical menu">
          
          {% for h in empleado.habilidades.all %}
            {{ h.habilidad }}
            
          {% endfor %}
            

        </ul>
  
      </div>
    </div>
  </div>
</div>




{% endblock content %}

templates/persona/habilidades.html
<h1>habilidades del empleado</h1>

<form action="" method="GET">{% csrf_token %}
    <input type="text" id="nombre" name="nombre" placeholder="ingresa nombre">
    <button type="submit">buscar</button>   
</form>

<ul>

    
    {% for h in habilidades %}
        <li>{{h}}</li>
    {% endfor %}
        
</ul>

templates/persona/list_all.html
{% extends 'base.html' %}





{% block content %}
{% include 'includes/header.html' %}
<!-- listamos todos los elementos-->

<div class="grid-container" >
    <div class="grid-x">
        <h1 class="cell">Lista de empleados</h1>
   
    <form class="cell grid-x grid-margin-x"  method="GET">{% csrf_token %}
            <div class="cell large-7"> 
                <input type="text" id="kword" name="kword" placeholder="Buscar empleado">
            </div>  
            <div cell large-7>
                <button class="submit success button">Buscar</button>
            </div>
    </form>   

            <div class="cell">  
                <table>
                    <thead>
                      <tr>
                        <th width="200">id</th>
                        <th>Nombres</th>
                        <th width="150">Apellidos</th>
                        <th width="150">departamento</th>
                        <th width="150">accion</th>

                      </tr>
                    </thead>
                    <tbody>
                        {% for e in empleados %}
                      <tr>
                        <td>{{e.id}}</td>
                        <td>{{e.first_name}}</td>
                        <td>{{e.last_name}}</td>
                        <td>{{e.departamento}}</td>
                        <td><a class="button warning" href="{% url 'persona_app:empleado_detail' e.id %}">Ver</a></td>

                        
                      </tr>
                      {% endfor %} 
                      
                    </tbody>
                  </table>
            
            </div>    
        </div>     
    </div>
 
    <div class="cell">
        
        {% if is_paginated %}
            <nav aria-label="Pagination">
                <ul class="pagination">
                    
                    {% if page_obj.has_previous %}
                    <li class="pagination-previous disabled">
                        <a href="?page={{page_obj.previous_page_number}}" >Atras</a> 
                    </li>

                    {% endif %}
                   
                    
                    {% for pagina in paginator.page_range %}
                        {% if pagina == page_obj.number %} 
                        <li class="current"><span class="show-for-sr">You're on page</span> {{pagina}}</li>  
                        {% else %}     
                        <li><a href="?page={{pagina}}" >{{ pagina }}</a></li>
                        {% endif %}
                    {% endfor %}
                        
                
                    {% if page_obj.has_next %}
                <li class="pagination-next">
                    <a href="?page={{page_obj.next_page_number}}" >Siguiente</a>  
                </li>
                    {% endif %}

                </ul>
            </nav>
        {% endif %}
            
       
    </div>



      



</div>



{% endblock content %}
    

templates/persona/list_by_area.html
{% extends 'base.html' %}


{% block title %}
        lista de empleados por departamento
{% endblock title %}



{% block content %}
    {% include 'includes/header.html' %}

    <div class="grid-container">
        <div class="grid-x">

            <div class="cell">
                <div class="cell">  
                    <table>
                        <thead>
                          <tr>
                            <th width="200">id</th>
                            <th>Nombres</th>
                            <th width="150">Apellidos</th>
                            <th width="150">departamento</th>
                            <th width="150">accion</th>
    
                          </tr>
                        </thead>
                        <tbody>
                            {% for e in empleados %}
                          <tr>
                            <td>{{e.id}}</td>
                            <td>{{e.first_name}}</td>
                            <td>{{e.last_name}}</td>
                            <td>{{e.departamento}}</td>
                            <td><a class="button warning" href="{% url 'persona_app:empleado_detail' e.id %}">Ver</a></td>
    
                            
                          </tr>
                          {% endfor %} 
                          
                        </tbody>
                      </table>
                
                </div>    
                
            </div>

        </div>
    </div>



{% endblock content %}
    


<h1>aqui estamos</h1>
{{object_list}}
<!-- listamos todos los elementos-->
<ul> 
    {% for e in object_list %}
        <li>{{e}}</li>
    {% endfor %}     
</ul>

templates/persona/list_by_kword.html
<h1>buscar empleado por palabvraclave</h1>

<form action="" method="GET">{% csrf_token %}
    <input type="text" id="kword" name="kword" placeholder="ingresa nombre">
    <button type="submit">buscar</button>   
</form>

<h3>lista de resultados</h3>

<ul>
{% for e in empleado %}
    <li>{{e}}</li>
{% endfor %}
    
</ul>

templates/persona/list_by_work.html
<h1>aqui estamos</h1>
{{object_list}}

<!-- listamos todos los elementos-->
<ul> 
    {% for e in object_list %}
        <li>{{e}}</li>
    {% endfor %}     
    
</ul>

templates/persona/lista_empleados.html
{% extends 'base.html' %}





{% block content %}
{% include 'includes/header.html' %}
<!-- listamos todos los elementos-->

<div class="grid-container" >
    <div class="grid-x">
        <h1 class="cell">Lista de empleados</h1>
   
 

            <div class="cell">  
                <table>
                    <thead>
                      <tr>
                        <th width="200">id</th>
                        <th>Nombres</th>
                        <th width="150">Apellidos</th>
                        <th width="150">departamento</th>
                        <th width="150">accion</th>

                      </tr>
                    </thead>
                    <tbody>
                        {% for e in empleados %}
                      <tr>
                        <td>{{e.id}}</td>
                        <td>{{e.first_name}}</td>
                        <td>{{e.last_name}}</td>
                        <td>{{e.departamento}}</td>
                        <td>
                            <a class="button success" href="{% url 'persona_app:update' e.id %}">editar</a>
                        </td>
                        <td>
                            <a class="button alert" href="{% url 'persona_app:delete' e.id %}">eliminar</a>
                        </td>

                        
                      </tr>
                      {% endfor %} 
                      
                    </tbody>
                  </table>
            
            </div>    
        </div>     
    </div>
 
    <div class="cell">
        
        {% if is_paginated %}
            <nav aria-label="Pagination">
                <ul class="pagination">
                    
                    {% if page_obj.has_previous %}
                    <li class="pagination-previous disabled">
                        <a href="?page={{page_obj.previous_page_number}}" >Atras</a> 
                    </li>

                    {% endif %}
                   
                    
                    {% for pagina in paginator.page_range %}
                        {% if pagina == page_obj.number %} 
                        <li class="current"><span class="show-for-sr">You're on page</span> {{pagina}}</li>  
                        {% else %}     
                        <li><a href="?page={{pagina}}" >{{ pagina }}</a></li>
                        {% endif %}
                    {% endfor %}
                        
                
                    {% if page_obj.has_next %}
                <li class="pagination-next">
                    <a href="?page={{page_obj.next_page_number}}" >Siguiente</a>  
                </li>
                    {% endif %}

                </ul>
            </nav>
        {% endif %}
            
       
    </div>



      



</div>



{% endblock content %}
    

templates/persona/sucess.html
<h1> Felicitaciones, se agrego correctamente el empleado</h1>

templates/persona/update.html
{% extends 'base.html' %}

{% block title %}

    Editar empleado
    
{% endblock title %}
    


{% block content %}
    {% include 'includes/header.html' %}


    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell"> 
                Modificar empleado
            </h1>
            <div class="cell">
                <form class="grid-x grid-margin-x" action="" method="post" enctype="multipart/form-data">{% csrf_token %}
                    <div class=" cell large-6 ">
                        <label>Nombres{{ form.first_name }}
                        </label>
                    </div>
                    <div class=" cell large-6 ">
                        <label>Apellidos{{ form.last_name }}
                        </label>
                    </div>
                    <div class=" cell large-6 ">
                        <label>trabajo{{ form.job }}
                        </label>
                    </div>
                    <div class=" cell large-6 ">
                        <label>Departamento{{ form.departamento }}
                        </label>
                    </div>
                    <div class=" cell large-6 ">
                        <label>Habilidades{{ form.habilidades }}
                        </label>
                    </div>
                    
                    
                    <div class=" cell large-12">
                        <button  type="submit" class="submit success button">actualizar</button>
                    </div>
                
                    
                </form>
            </div>

        </div>    
    </div>
{% endblock content %}
    