applications/departamento/urls.py
from django.urls import path
from . import views

app_name = 'departamento_app'

urlpatterns = [

    path('lista_departamento/', views.DepartamentoListView.as_view(),name="lista_departamento"),


    path('new-departamento/', views.NewDepartamenView.as_view(),name="new_departamento"),





]

applications/persona/urls.py
from django.urls import path
from . import views

# le damos un nombre a todas las urls
app_name = 'persona_app'

urlpatterns = [
    #incio base de tempaltes
        path('', views.InicioView.as_view(), name='inicio' ),



    #list views
    path('listar-todo-empleado/', views.ListAllEmpleados.as_view(), name="empleados_all"),

    path('listar-empleado-admin/', views.ListAllEmpleadosAdmin.as_view(), name="empleados_admin"),

    
    path('listar-by-area/<short_name>', views.ListByArea.as_view(),name='empleado_area'),
    path('listar-by-work/<job>', views.ListByWork.as_view()),
    path('listar-by-kword/', views.ListarEmpleadoPorPalabraClave.as_view()),
    path('listar-by-habilidades/', views.ListHabilidadesEmpleados.as_view()),


    #details view
    
    path('ver-empleado/<pk>', views.EmpleadoDetailView.as_view(), name='empleado_detail'),
    
    #create view
    
    path('add_empleado/', views.EmpleadoCreateView.as_view(), name="add_empleado"),


    #                                                  le etiqueda name nos da la oportunidad de referirnos a esta url mediante el resver_lazy
    path('sucess/', views.SusscessView.as_view(), name='correcto' ),
    #update view
    path('update/<pk>', views.EmpleadoUpdateView.as_view(), name='update' ),
    #deleteview
    path('delete/<pk>', views.EmpleadoDeleteView.as_view(), name='delete' ),





   


]

empleado/urls.py
from django.contrib import admin
from django.urls import path, include
from applications.home.views import IndexView
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    #home
    path('', include('applications.home.urls')),
    path('', include('applications.persona.urls')),
    path('', include('applications.departamento.urls')),



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/header.html
<div class="top-bar">
    <div class="top-bar-left">
      <ul class="dropdown menu" data-dropdown-menu>
        <li class="menu-text">Empleados</li>

        <li><a href="{% url 'persona_app:empleados_all' %}">Listar</a></li>

        <li><a href="{% url 'departamento_app:lista_departamento' %}">Departamento</a></li>
        <li><a href="{% url 'persona_app:empleados_admin' %}">Administrar</a></li>
        <li><a href="{% url 'departamento_app:new_departamento' %}">Registrar nuevo departamento</a></li>

      </ul>
    </div>
    <div class="top-bar-right">
      <ul class="menu">
        <li><input type="search" placeholder="buscar empleado"></li>
        <li><a href="{% url 'persona_app:add_empleado' %}" type="button" class="button">registrar Nuevo</a></li>
      </ul>
    </div>
  </div>