applications/departamento/urls.py
from django.urls import path
from . import views

app_name = 'departamento_app'

urlpatterns = [

    path('lista_departamento/', views.DepartamentoListView.as_view(),name="lista_departamento"),


    path('new-departamento/', views.NewDepartamenView.as_view(),name="new_departamento"),





]

applications/persona/urls.py
from django.urls import path
from . import views

# le damos un nombre a todas las urls
app_name = 'persona_app'

urlpatterns = [
    #incio base de tempaltes
        path('', views.InicioView.as_view(), name='inicio' ),



    #list views
    path('listar-todo-empleado/', views.ListAllEmpleados.as_view(), name="empleados_all"),

    path('listar-empleado-admin/', views.ListAllEmpleadosAdmin.as_view(), name="empleados_admin"),

    
    path('listar-by-area/<short_name>', views.ListByArea.as_view(),name='empleado_area'),
    path('listar-by-work/<job>', views.ListByWork.as_view()),
    path('listar-by-kword/', views.ListarEmpleadoPorPalabraClave.as_view()),
    path('listar-by-habilidades/', views.ListHabilidadesEmpleados.as_view()),


    #details view
    
    path('ver-empleado/<pk>', views.EmpleadoDetailView.as_view(), name='empleado_detail'),
    
    #create view
    
    path('add_empleado/', views.EmpleadoCreateView.as_view(), name="add_empleado"),


    #                                                  le etiqueda name nos da la oportunidad de referirnos a esta url mediante el resver_lazy
    path('sucess/', views.SusscessView.as_view(), name='correcto' ),
    #update view
    path('update/<pk>', views.EmpleadoUpdateView.as_view(), name='update' ),
    #deleteview
    path('delete/<pk>', views.EmpleadoDeleteView.as_view(), name='delete' ),





   


]

empleado/urls.py
from django.contrib import admin
from django.urls import path, include
from applications.home.views import IndexView
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    #home
    path('', include('applications.home.urls')),
    path('', include('applications.persona.urls')),
    path('', include('applications.departamento.urls')),



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/departamento/models.py
from django.db import models

# Create your models here.
class Departamento(models.Model):
    name = models.CharField('Nombre', max_length=50)
    short_name = models.CharField('Nombre Corto', max_length=20, unique=True)
    anulate = models.BooleanField('Anulado', default=False )

    class Meta():
        verbose_name = 'Mi departamento'
        verbose_name_plural = 'Areas de la empresa'
        ordering = ['-name']
        unique_together = ('name','short_name')
        


    def __str__(self):
        return str(self.id) + '-' + self.name + '-' + self.short_name    

applications/departamento/forms.py
from django import forms
#creamos el formulario de esta manera

class NewDepartamentoForm(forms.Form):
    #usamos el plugin para cf para hacer los campos de charfield
    nombre = forms.CharField(max_length=50)
    apellido = forms.CharField(max_length=50)
    departamento = forms.CharField(max_length=50)
    short_name_departamento = forms.CharField(max_length=20)

applications/departamento/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic import ListView
from django.views.generic.edit import FormView
from .forms import NewDepartamentoForm
from applications.persona.models import Empleado
from .models import Departamento
# Create your views here.


class DepartamentoListView(ListView):
    model = Departamento
    template_name = "departamento/lista_departamento.html"
    context_object_name = "departamentos"

class NewDepartamenView(FormView):
    template_name = 'departamento/new_departamento.html'
    form_class = NewDepartamentoForm
    success_url = '/'

    def form_valid(self, form):
        #logiica
        print('estamos en el form valid')

        #creamops una intancia para con los datos recuperadospara ser utilizado en la creacion del empleado
        depa= Departamento(
            name=form.cleaned_data['departamento'],
            short_name=form.cleaned_data['short_name_departamento']

        )
        depa.save()


        nombre = form.cleaned_data['nombre']
        apellido = form.cleaned_data['apellido']

        Empleado.objects.create(
            first_name = nombre,
            last_name = apellido,
            job = '1',
            departamento = depa

        )

        return super(NewDepartamenView, self).form_valid(form)

templates/departamento/lista_departamento.html
{% extends 'base.html' %}


{% block title %}
    Lista departamentos
{% endblock title %}


{% block content %}
{% include 'includes/header.html' %}
    
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista de departamentos de la empresa</h1>
        <div class="cell">
        
            <table>
                <tbody>
                    
                    {% for departamento  in departamentos %}
                        
              
                        
                    <tr>
                        <td>{{departamento.name}}</td>
                        <td>{{departamento.short_name}}</td>
                        <td><a class="button warning" href="{% url 'persona_app:empleado_area' departamento.short_name %}">Ver empleados</a></td>

                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            
        </div>
    </div>
</div>

{% endblock content %}
    
    

templates/departamento/new_departamento.html
{% extends 'base.html' %}


{% block title %}
    Registrar departamento
{% endblock title %}
    


{% block content %}
    

{% include 'includes/header.html' %}


    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Registrar departamento</h1>
            <form class="cell callout grid-x grid-margin-x" method="POST"> {% csrf_token %}
                <div class="medium-6 cell">
                    <label>Nombre:
                            {{form.nombre}}
                    </label>
                </div> 
                <div class="medium-6 cell">
                    <label>Apellido:
                            {{form.nombre}}
                    </label>
                </div> 
                <div class="medium-6 cell">
                    <label>Trabajo:
                            {{form.nombre}}
                    </label>
                </div> 
                <div class="medium-6 cell">
                    <label>Departamento:
                            {{form.nombre}}
                    </label>
                </div> 
                <div class="medium-6 cell">
                    <label>Shortname:
                            {{form.nombre}}
                    </label>
                </div> 
                
                <div class="medium-8 cell">
                    <button class="button success" type="submit"> Guardar </button>
                </div> 
            </form>
        </div>
    </div>

{% endblock content %}
    